name: fraudx

services:
  controller-1:
    image: apache/kafka:4.1.0
    hostname: controller-1
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m -XX:+UseG1GC"
    mem_limit: 1g
    mem_swappiness: 0
    volumes:
      - kafka-data-controller-1:/var/lib/kafka
    networks:
      - fraudx-net

  controller-2:
    image: apache/kafka:4.1.0
    hostname: controller-2
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m -XX:+UseG1GC"
    mem_limit: 1g
    mem_swappiness: 0
    volumes:
      - kafka-data-controller-2:/var/lib/kafka
    networks:
      - fraudx-net

  controller-3:
    image: apache/kafka:4.1.0
    hostname: controller-3
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m -XX:+UseG1GC"
    mem_limit: 1g
    mem_swappiness: 0
    volumes:
      - kafka-data-controller-3:/var/lib/kafka
    networks:
      - fraudx-net

  broker-1:
    image: apache/kafka:4.1.0
    hostname: broker-1
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:19092,HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker-1:19092,HOST://localhost:9004
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms2g -XX:MetaspaceSize=96m -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -XX:+ExplicitGCInvokesConcurrent -XX:+UseG1GC -XX:G1HeapRegionSize=2M -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_NETWORK_THREADS: 5
    ports:
      - "9004:9092"
    mem_limit: 3g
    mem_swappiness: 0
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - kafka-data-broker-1:/var/lib/kafka
    networks:
      - fraudx-net
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-2:
    image: apache/kafka:4.1.0
    hostname: broker-2
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:19092,HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker-2:19092,HOST://localhost:9005
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms2g -XX:MetaspaceSize=96m -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -XX:+ExplicitGCInvokesConcurrent -XX:+UseG1GC -XX:G1HeapRegionSize=2M -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_NETWORK_THREADS: 5
    ports:
      - "9005:9092"
    mem_limit: 3g
    mem_swappiness: 0
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - kafka-data-broker-2:/var/lib/kafka
    networks:
      - fraudx-net
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-3:
    image: apache/kafka:4.1.0
    hostname: broker-3
    environment:
      CLUSTER_ID: local-cluster
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:19092,HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker-3:19092,HOST://localhost:9006
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms2g -XX:MetaspaceSize=96m -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -XX:+ExplicitGCInvokesConcurrent -XX:+UseG1GC -XX:G1HeapRegionSize=2M -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_NETWORK_THREADS: 5
    ports:
      - "9006:9092"
    mem_limit: 3g
    mem_swappiness: 0
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - kafka-data-broker-3:/var/lib/kafka
    networks:
      - fraudx-net
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:19092,broker-2:19092,broker-3:19092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - 8888:8080
    mem_limit: 1g
    networks:
      - fraudx-net
    depends_on:
      - broker-1
      - broker-2
      - broker-3

  payment-service:
    build: ./payment-service
    environment:
      SPRING_APPLICATION_NAME: payment-service
      SPRING_APPLICATION_JSON: '{"logging.level.com.example.payment":"INFO"}'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker-1:19092,broker-2:19092,broker-3:19092
      SPRING_KAFKA_PRODUCER_COMPRESSION_TYPE: lz4
      SPRING_KAFKA_PRODUCER_BUFFER_MEMORY: 134217728
      SPRING_KAFKA_PRODUCER_BATCH_SIZE: 1048576
      SPRING_KAFKA_PRODUCER_LINGER_MS: 50
      SPRING_KAFKA_PRODUCER_ACKS: 1
      KAFKA_TOPICS_PAYMENT_NAME: payment-events
      KAFKA_TOPICS_PAYMENT_PARTITIONS: 9
      KAFKA_TOPICS_PAYMENT_REPLICATION_FACTOR: 3
    ports:
      - 8080:8080
    mem_limit: 3g
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    networks:
      - fraudx-net
    depends_on:
      - broker-1
      - broker-2
      - broker-3

  fraud-detection-service:
    build: ./fraud-detection-service
    environment:
      SPRING_APPLICATION_NAME: fraud-detection-service
      SPRING_APPLICATION_JSON: '{"logging.level.com.example.frauddetection":"INFO"}'
      SPRING_CONFIG_IMPORT: rules.yaml
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker-1:19092,broker-2:19092,broker-3:19092
      SPRING_KAFKA_CONSUMER_GROUP_ID: fraud-detection
      SPRING_KAFKA_CONSUMER_FETCH_MIN_SIZE: 1048576
      SPRING_KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 10485760
      SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: false
      SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS: 3000
      SPRING_KAFKA_CONSUMER_CONCURRENCY: 9
      KAFKA_TOPICS_PAYMENT_NAME: payment-events
    ports:
      - 8081:8080
    mem_limit: 4g
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    networks:
      - fraudx-net
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      - scylladb-init

  scylladb-1:
    image: scylladb/scylla
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      memlock: -1
      nofile:
        soft: 1048576
        hard: 1048576
    command: --reactor-backend=epoll --cpuset=0,3,9 --memory 5G --smp 3
    volumes:
      - scylladb-data-1:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
    ports:
      - "9041:9042"
    mem_limit: 7g
    networks:
      fraudx-net:
        ipv4_address: 192.168.1.101
    healthcheck:
      test: ["CMD-SHELL", "nodetool -h 192.168.1.101 status | grep 192.168.1.101 | grep UN"]
      interval: 0.5s
      timeout: 30s
      retries: 60

  scylladb-2:
    image: scylladb/scylla
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      memlock: -1
      nofile:
        soft: 1048576
        hard: 1048576
    command: --reactor-backend=epoll --seeds=192.168.1.101 --cpuset=1,4,10  --memory 5G --smp 3
    volumes:
      - scylladb-data-2:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
    ports:
      - "9042:9042"
    mem_limit: 7g
    networks:
      fraudx-net:
        ipv4_address: 192.168.1.102
    depends_on:
      - scylladb-1
    healthcheck:
      test: ["CMD-SHELL", "nodetool -h 192.168.1.102 status | grep 192.168.1.102 | grep UN"]
      interval: 0.5s
      timeout: 30s
      retries: 60

  scylladb-3:
    image: scylladb/scylla
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nproc: 65535
      memlock: -1
      nofile:
        soft: 1048576
        hard: 1048576
    command: --reactor-backend=epoll --seeds=192.168.1.101 --cpuset=2,5,11 --memory 5G --smp 3
    volumes:
      - scylladb-data-3:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
    ports:
      - "9043:9042"
    mem_limit: 7g
    networks:
      fraudx-net:
        ipv4_address: 192.168.1.103
    depends_on:
      - scylladb-1
    healthcheck:
      test: ["CMD-SHELL", "nodetool -h 192.168.1.103 status | grep 192.168.1.103 | grep UN"]
      interval: 0.5s
      timeout: 30s
      retries: 60

  scylladb-init:
    image: scylladb/scylla
    depends_on:
      scylladb-1:
        condition: service_healthy
      scylladb-2:
        condition: service_healthy
      scylladb-3:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
        cqlsh 192.168.1.101 9042 -e \"CREATE KEYSPACE IF NOT EXISTS fraudx WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': 3};\" &&
        echo '✅ Keyspace fraudx created'
      "
    networks:
      - fraudx-net

volumes:
  kafka-data-controller-1:
  kafka-data-controller-2:
  kafka-data-controller-3:
  kafka-data-broker-1:
  kafka-data-broker-2:
  kafka-data-broker-3:
  scylladb-data-1:
  scylladb-data-2:
  scylladb-data-3:

networks:
  fraudx-net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
