name: fraudx

services:
  broker-1:
    environment:
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/usr/share/jmx_exporter/kafka-config.yaml
    volumes:
      - ./monitoring/jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./monitoring/jmx-exporter/kafka-config.yaml:/usr/share/jmx_exporter/kafka-config.yaml
    ports:
      - "7071:7071"

  broker-2:
    environment:
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/usr/share/jmx_exporter/kafka-config.yaml
    volumes:
      - ./monitoring/jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./monitoring/jmx-exporter/kafka-config.yaml:/usr/share/jmx_exporter/kafka-config.yaml
    ports:
      - "7072:7071"

  broker-3:
    environment:
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/usr/share/jmx_exporter/kafka-config.yaml
    volumes:
      - ./monitoring/jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./monitoring/jmx-exporter/kafka-config.yaml:/usr/share/jmx_exporter/kafka-config.yaml
    ports:
      - "7073:7071"

  payment-service:
    environment:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info"

  fraud-detection-service:
    environment:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fraudx-net
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      - payment-service
      - fraud-detection-service

  grafana:
    image: grafana/grafana:12.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - fraudx-net
    depends_on:
      - prometheus

volumes:
  grafana-data:
