spring:
  application:
    name: payment-service
  config:
    import:
      - classpath:rules.yaml
  kafka:
    bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
    producer:
      key-serializer: com.example.payment.adapter.KafkaProtobufSerializer
      value-serializer: com.example.payment.adapter.KafkaProtobufSerializer
      linger-ms: 5
    admin:
      auto-create: true
      fail-fast: false

kafka:
  topics:
    payment:
      name: payment-events
      partitions: 4
      replication-factor: 3