spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9004,localhost:9005
    producer:
      acks: 1
      batch-size: 1048576           # 1MB
      buffer-memory: 134217728      # 128MB

kafka:
  connect: false
  topics:
    payment:
      name: payment-events
      partitions: 8
      replication-factor: 1