spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9004,localhost:9005
    producer:
      acks: 1
      batch-size: 1048576           # 1MB
      buffer-memory: 134217728      # 128MB

kafka:
  connect: false
  topic-config:
    payment: 
      topic-name: payment-events
      partitions: 4
      replication-factor: 2