lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(Count|Value|OneMinuteRate|75thPercentile|99thPercentile)
    name: kafka_$1_$2_$3_$4
    type: GAUGE
  - pattern: java.lang<type=(.+), name=(.+)><>(.+)
    name: java_lang_$1_$2_$3
