global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'controller-1:7071'
          - 'controller-2:7071'
          - 'controller-3:7071'
          - 'broker-1:7071'
          - 'broker-2:7071'
          - 'broker-3:7071'

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'payment-service:8080'
          - 'fraud-detection-service:8080'
