spring:
  application:
    name: fraud-detection-service
  config:
    import:
      - rules.yaml
  kafka:
    bootstrap-servers: localhost:9004,localhost:9005,localhost:9006
    consumer:
      group-id: fraud-detection
      fetch-min-size: 1048576 # 1MB
      max-partition-fetch-bytes: 10485760 # 10MB
      enable-auto-commit: false
      concurrency: 4
      max-poll-records: 50000

kafka:
  topics:
    payment:
      name: payment-events