datastax-java-driver {
    advanced {
        connection {
            pool.local.size = 32
        }
        max-requests-per-connection = 32767
        socket.keep-alive = true
        protocol.compression = lz4
    }
}