spring:
  application:
    name: fraud-detection-service
  config:
    import:
      - rules.yaml
  kafka:
    bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
    consumer:
      group-id: fraud-detection
      fetch-min-size: 1
      max-partition-fetch-bytes: 1048576
      enable-auto-commit: true
      max-poll-records: 500
      concurrency: 4
  cassandra:
    contact-points: scylladb-1,scylladb-2,scylladb-3
    local-datacenter: datacenter1
    keyspace-name: fraudx

kafka:
  topics:
    payment:
      name: payment-events
