spring:
  application:
    name: fraud-detection-service
  kafka:
    bootstrap-servers: localhost:9004,localhost:9005
    consumer:
      group-id: fraud-detection-dev
      auto-offset-reset: earliest
      enable-auto-commit: false
      concurrency: 4
      poll-timeout: 5000

kafka:
  topics:
    payment:
      name: payment-events